# Generated by Django 4.1.3 on 2023-08-23 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0002_customer_vendor_remove_customerpermission_users_and_more'),
        ('vendors', '0003_remove_order_vendor_orderitem_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myuser.vendor'),
        ),
        migrations.AlterField(
            model_name='vendorproduct',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myuser.vendor'),
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
