# Generated by Django 4.1.3 on 2023-08-24 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_alter_orderitem_vendor_alter_vendorproduct_vendor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='vendor',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
