# Generated by Django 4.2.3 on 2023-09-07 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Total',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
