# Generated by Django 4.2.3 on 2023-09-07 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
