# Generated by Django 4.1.3 on 2023-08-24 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_cartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='product',
            new_name='products',
        ),
    ]
